name = "test-app"
compatibility_date = "2024-11-18"

# For SvelteKit applications using adapter-cloudflare
main = ".svelte-kit/output/server/index.js"
assets = { directory = ".svelte-kit/output/client", binding = "ASSETS" }

[build]
command = "npm run build"

[[routes]]
pattern = "/*"
custom_domain = false 